# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blog.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='blog.proto',
  package='blog',
  syntax='proto3',
  serialized_options=b'Z\034github.com/repo/demo/go/blog',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nblog.proto\x12\x04\x62log\"\x1b\n\rGetOneRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"N\n\x0eGetOneResponse\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x1c\n\x06\x61uthor\x18\x03 \x01(\x0b\x32\x0c.blog.Author\"/\n\x06\x41uthor\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\"1\n\x12ListByQueryRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\r\n\x05query\x18\x02 \x01(\t\"4\n\x13ListByQueryResponse\x12\x1d\n\x05posts\x18\x01 \x03(\x0b\x32\x0e.blog.ListItem\"L\n\x08ListItem\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x1c\n\x06\x61uthor\x18\x03 \x01(\x0b\x32\x0c.blog.Author2\x8a\x01\n\x0f\x42logPostService\x12\x33\n\x06GetOne\x12\x13.blog.GetOneRequest\x1a\x14.blog.GetOneResponse\x12\x42\n\x0bListByQuery\x12\x18.blog.ListByQueryRequest\x1a\x19.blog.ListByQueryResponseB\x1eZ\x1cgithub.com/repo/demo/go/blogb\x06proto3'
)




_GETONEREQUEST = _descriptor.Descriptor(
  name='GetOneRequest',
  full_name='blog.GetOneRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='blog.GetOneRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=47,
)


_GETONERESPONSE = _descriptor.Descriptor(
  name='GetOneResponse',
  full_name='blog.GetOneResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='blog.GetOneResponse.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='blog.GetOneResponse.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='author', full_name='blog.GetOneResponse.author', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=127,
)


_AUTHOR = _descriptor.Descriptor(
  name='Author',
  full_name='blog.Author',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_name', full_name='blog.Author.first_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='blog.Author.last_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=176,
)


_LISTBYQUERYREQUEST = _descriptor.Descriptor(
  name='ListByQueryRequest',
  full_name='blog.ListByQueryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='page', full_name='blog.ListByQueryRequest.page', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='query', full_name='blog.ListByQueryRequest.query', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=227,
)


_LISTBYQUERYRESPONSE = _descriptor.Descriptor(
  name='ListByQueryResponse',
  full_name='blog.ListByQueryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='posts', full_name='blog.ListByQueryResponse.posts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=281,
)


_LISTITEM = _descriptor.Descriptor(
  name='ListItem',
  full_name='blog.ListItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='blog.ListItem.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='blog.ListItem.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='author', full_name='blog.ListItem.author', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=359,
)

_GETONERESPONSE.fields_by_name['author'].message_type = _AUTHOR
_LISTBYQUERYRESPONSE.fields_by_name['posts'].message_type = _LISTITEM
_LISTITEM.fields_by_name['author'].message_type = _AUTHOR
DESCRIPTOR.message_types_by_name['GetOneRequest'] = _GETONEREQUEST
DESCRIPTOR.message_types_by_name['GetOneResponse'] = _GETONERESPONSE
DESCRIPTOR.message_types_by_name['Author'] = _AUTHOR
DESCRIPTOR.message_types_by_name['ListByQueryRequest'] = _LISTBYQUERYREQUEST
DESCRIPTOR.message_types_by_name['ListByQueryResponse'] = _LISTBYQUERYRESPONSE
DESCRIPTOR.message_types_by_name['ListItem'] = _LISTITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetOneRequest = _reflection.GeneratedProtocolMessageType('GetOneRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETONEREQUEST,
  '__module__' : 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.GetOneRequest)
  })
_sym_db.RegisterMessage(GetOneRequest)

GetOneResponse = _reflection.GeneratedProtocolMessageType('GetOneResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETONERESPONSE,
  '__module__' : 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.GetOneResponse)
  })
_sym_db.RegisterMessage(GetOneResponse)

Author = _reflection.GeneratedProtocolMessageType('Author', (_message.Message,), {
  'DESCRIPTOR' : _AUTHOR,
  '__module__' : 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.Author)
  })
_sym_db.RegisterMessage(Author)

ListByQueryRequest = _reflection.GeneratedProtocolMessageType('ListByQueryRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTBYQUERYREQUEST,
  '__module__' : 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.ListByQueryRequest)
  })
_sym_db.RegisterMessage(ListByQueryRequest)

ListByQueryResponse = _reflection.GeneratedProtocolMessageType('ListByQueryResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTBYQUERYRESPONSE,
  '__module__' : 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.ListByQueryResponse)
  })
_sym_db.RegisterMessage(ListByQueryResponse)

ListItem = _reflection.GeneratedProtocolMessageType('ListItem', (_message.Message,), {
  'DESCRIPTOR' : _LISTITEM,
  '__module__' : 'blog_pb2'
  # @@protoc_insertion_point(class_scope:blog.ListItem)
  })
_sym_db.RegisterMessage(ListItem)


DESCRIPTOR._options = None

_BLOGPOSTSERVICE = _descriptor.ServiceDescriptor(
  name='BlogPostService',
  full_name='blog.BlogPostService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=362,
  serialized_end=500,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetOne',
    full_name='blog.BlogPostService.GetOne',
    index=0,
    containing_service=None,
    input_type=_GETONEREQUEST,
    output_type=_GETONERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ListByQuery',
    full_name='blog.BlogPostService.ListByQuery',
    index=1,
    containing_service=None,
    input_type=_LISTBYQUERYREQUEST,
    output_type=_LISTBYQUERYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BLOGPOSTSERVICE)

DESCRIPTOR.services_by_name['BlogPostService'] = _BLOGPOSTSERVICE

# @@protoc_insertion_point(module_scope)
