# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import blog_pb2 as blog__pb2


class BlogPostServiceStub(object):
    """Define the service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOne = channel.unary_unary(
                '/blog.BlogPostService/GetOne',
                request_serializer=blog__pb2.GetOneRequest.SerializeToString,
                response_deserializer=blog__pb2.GetOneResponse.FromString,
                )


class BlogPostServiceServicer(object):
    """Define the service
    """

    def GetOne(self, request, context):
        """Add methods to the services
        Here the communication type is the simplest 'Unary rpc'
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlogPostServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOne': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOne,
                    request_deserializer=blog__pb2.GetOneRequest.FromString,
                    response_serializer=blog__pb2.GetOneResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'blog.BlogPostService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BlogPostService(object):
    """Define the service
    """

    @staticmethod
    def GetOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blog.BlogPostService/GetOne',
            blog__pb2.GetOneRequest.SerializeToString,
            blog__pb2.GetOneResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
